### ISSUE TITLE
Option to modify the bootstrap urls in logview.ftl

### ISSUE THREAD

**Issue by jgoldhammer** [lukashinsch/spring-boot-actuator-logview#20]
Hi,

thanks for providing such a great addon. Would it be possible to replace the links to the bootstrap files in your logview.ftl?

Default is cdn-url, but it would be nice to be able to overwrite this in your configuration?

We have a very restrictive Content-Security-Policy in our environment, so I don´t want to use the maxcdn provider.

Thanks,
Jens

**Comment by lukashinsch** [comment]
Hi Jens,

I'm glad you like my little project.

I agree that configuring external urls would be helpful. I'm thinking of having an (optional) list of urls in the config that completely overrides the external styles that are included. That would give you complete freedom to switch versions or to substitute your own design.

What do you think?

Lukas

**Comment by jgoldhammer** [comment]
Thanks Lukas for your response. 
A first step would be to have these two urls configurable from outside via configuration, so that we can inject the href from outside- default would be your urls...

https://github.com/lukashinsch/spring-boot-actuator-logview/blob/master/lib/src/main/resources/templates/logview.ftl#L4
https://github.com/lukashinsch/spring-boot-actuator-logview/blob/master/lib/src/main/resources/templates/logview.ftl#L5

Sounds that reasonable to you? I want to have a quickwin now and include your addon very soon...

**Comment by lukashinsch** [comment]
closed in PR #21

**Comment by lukashinsch** [comment]
Just pushed a new release, should be available from maven central soon

**Comment by lukashinsch** [comment]
Hi Jens,
v. 0.2.9 is available from maven central. let me know if it works for you.
Regards
Lukas

**Comment by jgoldhammer** [comment]
Thank you, Lukas. Works great!
